BEGIN
declare @CHIEURONG float
declare @CHIEUDAI float
declare @CHUVI int
declare @DIENTICH int
set @CHUVI = 0
set @DIENTICH = 0
set @CHIEUDAI = 6
set @CHIEURONG = 3.0
select @CHUVI = (@CHIEURONG + @CHIEUDAI)*2
select @DIENTICH = (@CHIEURONG * @CHIEUDAI) 
PRINT ' CHU VI : ' + cast(@CHUVI as nvarchar)
PRINT ' DIEN TICH : ' + cast(@DIENTICH as nvarchar)
END
BEGIN
USE QLDA 
SELECT * FROM NHANVIEN WHERE LUONG = ( SELECT  MAX(LUONG) FROM NHANVIEN)
END
BEGIN
USE QLDA
DECLARE @PHONGNGHIENCUU TABLE (
HONV NVARCHAR(50),
TENLOT NVARCHAR(50),
TENNV NVARCHAR(50),
LUONG FLOAT)
INSERT INTO @PHONGNGHIENCUU (HONV,TENLOT,TENNV,LUONG)
SELECT HONV,TENLOT,TENNV,LUONG

FROM NHANVIEN
WHERE PHG = 5;
SELECT * FROM @PHONGNGHIENCUU
DECLARE @TB FLOAT
SET @TB =0
SELECT @TB = AVG(LUONG) FROM @PHONGNGHIENCUU
PRINT 'trung binh luong : ' + cast(@TB AS NVARCHAR)
SELECT * FROM @PHONGNGHIENCUU WHERE LUONG > @TB
END
BEGIN
USE  QLDA
SELECT pb.MAPHG,
       pb.TENPHG,
       COUNT(nv.MANV)      AS SoLuongNhanVien,
       AVG(nv.LUONG)       AS LuongTrungBinh
FROM PHONGBAN pb
JOIN NHANVIEN nv ON nv.PHG = pb.MAPHG
GROUP BY pb.MAPHG, pb.TENPHG
HAVING AVG(nv.LUONG) > 30000
ORDER BY LuongTrungBinh DESC
END
BEGIN
SELECT 
    pb.MAPHG,
    pb.TENPHG,
    COUNT(d.MADA) AS SoLuongDeAn
FROM PHONGBAN AS pb
LEFT JOIN DEAN AS d 
       ON d.PHONG = pb.MAPHG   -- cột "PHONG" trong bảng DEAN
GROUP BY 
    pb.MAPHG, 
    pb.TENPHG
ORDER BY 
    SoLuongDeAn DESC;
    
END
